[changelog]
body = """
{% set repo_url = "https://github.com/VLGBT/test" %}

{% for tag, commits in commits | group_by(attribute="tag") %}
## [{{ tag.name | default('Unreleased') }}] - {{ tag.date | default('Unreleased') }}

{% for group, group_commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}

{% for commit in group_commits %}
- {{ commit.message | trim }} ([{{ commit.id | truncate(length=7, end="") }}]({{ repo_url }}/commit/{{ commit.id }}))
{% endfor %}

{% endfor %}

{% endfor %}
"""
