[git]
repo_url = "https://github.com/VLGBT/test"

[changelog]
body = """
{% for commit in commits %}
- {{ commit.message | trim }} ([{{ commit.id | truncate(length=7, end="") }}]({{ git.repo_url }}/commit/{{ commit.id }}))
{% endfor %}
"""
