name: Changelog
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          parsist-credentials: True
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g conventional-changelog-cli
      - run: conventional-changelog -p angular -i CHANGELOG.md -s
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git push
