name: Auto Release

# Запускать при пуше тегов вида v1.2.3
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Опционально: установка Ruby для github-changelog-generator
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      # 3. Устанавливаем github-changelog-generator
      - name: Install Changelog Generator
        run: gem install github_changelog_generator

      # 4. Генерируем changelog для нового релиза
      - name: Generate Changelog
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          github_changelog_generator \
            --user ${{ github.repository_owner }} \
            --project ${{ github.event.repository.name }} \
            --future-release ${{ github.ref_name }} \
            --no-merge \
            --unreleased-only \
            --output temp_changelog.md
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat temp_changelog.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 5. Создаем GitHub Release с содержимым changelog
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
