name: Live Changelog
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  # чтобы можно было пушить обратно

      - name: Install git-cliff
        run: |
          curl -sSL https://github.com/orhun/git-cliff/releases/latest/download/git-cliff-x86_64-unknown-linux-gnu.tar.gz \
          | tar -xz
          sudo mv git-cliff /usr/local/bin/git-cliff

      - name: Generate changelog
        run: git cliff -o CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git diff --cached --quiet || (git commit -m "chore: update live changelog" && git push)
