# .github/workflows/update-changelog-unreleased.yml
name: «Обновление CHANGELOG — Unreleased»  
on:
  push:
    branches:
      - main

permissions:
  contents: write  # чтобы можно было коммитить файл

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # нужно полное состояние, чтобы можно было брать все коммиты

      - name: Extract commit messages since last release
        id: collect
        run: |
          # последний тэг версии, например v1.4.0
          LAST_TAG="$(git describe --tags --abbrev=0 || echo '')"
          echo "Last tag: $LAST_TAG"
          if [ -z "$LAST_TAG" ]; then
            # если тегов нет — взять всё
            RANGE="HEAD"
          else
            RANGE="$LAST_TAG..HEAD"
          fi
          echo "Range: $RANGE"
          COMMITS=$(git log --pretty=format:'%s' $RANGE)
          echo "$COMMITS"
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.md Unreleased section
        id: update
        run: |
          COMMITS="${{ steps.collect.outputs.commits }}"
          if [ -z "$COMMITS" ]; then
            echo "No new commits — nothing to do."
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Например: вставляем новую строку в секцию ## [Unreleased]
          awk -v commits="$COMMITS" '
            BEGIN { printed=0 }
            /^## \[Unreleased\]/ { print; printed=1; next }
            {
              if(printed==1 && /^## \[/){ printed=2 }
              if(printed==1){
                print("- " commits)
                printed=2
              }
              print
            }
          ' CHANGELOG.md > tmp && mv tmp CHANGELOG.md

          # проверка, действительно ли изменился файл
          if git diff --quiet CHANGELOG.md; then
            echo "No changes in CHANGELOG.md"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit & push changes
        if: steps.update.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update Unreleased in CHANGELOG.md"
          git push origin HEAD:main
