name: Live Changelog
on:
  push:
    branches:
      - main

permissions:
  contents: write  # чтобы Action мог пушить изменения в репозиторий

jobs:
  update‑changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml       # файл конфигурации (можешь назвать по‑другому)
          args: --verbose          # дополнительные аргументы, если хочешь
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit and push changelog
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git diff --cached --quiet || (git commit -m "chore: update live changelog" && git push)
