name: Generate Changelog
on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install git-cliff
        run: sudo apt-get install -y git-cliff
      - name: Generate changelog
        run: git cliff --tag ${{ github.ref_name }} -o CHANGELOG.md
      - name: Commit and push changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${{ github.ref_name }}"
          git push
